services:
  db:
    image: postgres:15-alpine
    container_name: ecoeats-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: affadine
      POSTGRES_DB: ecoeats
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api-express/Dockerfile
    container_name: ecoeats-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:affadine@db:5432/ecoeats?schema=public
      - DB_ADAPTER=postgresql
      - PORT=3000
    depends_on:
      - db

  client-web:
    build:
      context: .
      dockerfile: apps/client-web/Dockerfile
    container_name: ecoeats-client-web
    ports:
      - "5173:5173"
    depends_on:
      - api

  livreur-web:
    build:
      context: .
      dockerfile: apps/livreur-web/Dockerfile
    container_name: ecoeats-livreur-web
    ports:
      - "5174:5174"
    depends_on:
      - api

  restaurateur-web:
    build:
      context: .
      dockerfile: apps/restaurateur-web/Dockerfile
    container_name: ecoeats-restaurateur-web
    ports:
      - "5175:5175"
    depends_on:
      - api

  admin-web:
    build:
      context: .
      dockerfile: apps/admin-web/Dockerfile
    container_name: ecoeats-admin-web
    ports:
      - "5176:5176"
    depends_on:
      - api

volumes:
  pgdata:
